# Configuration file for data directory location
data_path: "../../../data"

# Options for manual encoder and decoder selection
enocders: ["onehot", "label", "ordinal"]
decoders: ["onehot", "label", "ordinal"]
# Configuration for the model
model:
  type: "GRU"
  input_shape: [100, 1]
  hidden_units: 64
  output_units: 10