# Configuration file for data directory location
data_path: 'C:\Users\rdbra\Documents\honoursProject\code_base\data\'

encoders: ["sequential", "valid_encoder"]
decoders: ["sequential", "valid_decoder"]
encoder_decoder_pairs:
- !!python/tuple
  - sequential
  - sequential


models: {
    "convautoencoder": {
        "encoder": "sequential",
        "decoder": "sequential",
    }
}

loss_functions: { "weighted_huber": [],}

