# Configuration file for data directory location
data_path: "../../../data"

# Options for manual encoder and decoder selection
enocders: ["onehot", "label", "ordinal"]
decoders: ["onehot", "label", "ordinal"]
# Configuration for the model
models: {
    "model1": {
        "encoder": "onehot",
        "decoder": "label",
        "params": {
            "layers": [64, 32],
            "activation": "relu"
        }
    },
    "model2": {
        "encoder": "label",
        "decoder": "ordinal",
        "params": {
            "layers": [128, 64],
            "activation": "tanh"
        }
    }
}