# Configuration file for data directory location
data_path: "../../../data"

enocders: ["Sequential"]
decoders: ["Sequential"]
encoder_decoder_pairs:
- !!python/tuple
  - Sequential
  - Sequential


models: {
    "ConvAutoencoder": {
        "encoder": "Sequential",
        "decoder": "Sequential",
    }
}

loss_functions: { "werighted_huber": [],}

